site_name: 'A Pomodoro Timer for&nbsp;GNOME'
site_url: https://gnomepomodoro.org
site_author: Kamil Prusko
site_description: Time management utility for GNOME
site_keywords:
    - gnome
    - gnome-shell
    - pomodoro
    - pomodoro timer
    - break timer
    - extension

repo_name: GitHub
repo_url: https://github.com/gnome-pomodoro/gnome-pomodoro-website/
edit_uri: "edit/master/docs/"

# Settings
site_dir: 'site'
docs_dir: 'docs'

theme:
    name: null
    custom_dir: 'theme/'
    language: 'en'

    static_templates:
        - 404.html

    include_search_page: false
    search_index_only: false

    navigation_depth: 2

plugins:
    # to get last revision date from git repo rather than page meta
    - git-revision-date-localized

    # allow sections to have their own pages
    - section-index

# Markdown extensions
# See https://python-markdown.github.io/extensions/
markdown_extensions:
    - attr_list
    - codehilite
    - def_list
    - extra
    - toc:
        permalink: true

# Strict mode doesn't work with section-index plugin
strict: false

nav:
    - Home: index.md
    - Download: download.md
    - User Guide:
        - docs/index.md
        - Getting Started: docs/getting-started.md
        - Preferences: docs/preferences.md
        - Integrations: docs/integrations.md
    - Get Involved:
        - docs/contributing/index.md
        - Development: docs/contributing/development.md
        - Documentation: docs/contributing/documentation.md
        - Translating: docs/contributing/translating.md
        - Maintanance: docs/contributing/maintainers.md
        - Report Issue: docs/contributing/report-issue.md

