
# Project information
site_name: 'A Pomodoro Timer for&nbsp;GNOME'
site_url: https://github.com/gnome-pomodoro/gnome-pomodoro/
site_author: Kamil Prusko
site_description: >-
  TODO

# Repository
repo_name: GitHub
repo_url: https://github.com/gnome-pomodoro/gnome-pomodoro/
edit_uri: "edit/master/docs/"

# Copyright
copyright: Copyright &copy; 2021 Kamil Prusko


site_dir: 'site'
docs_dir: 'docs'

theme:
    name: null
    custom_dir: 'theme/'
    language: 'en'

    static_templates:
        - 404.html

    include_search_page: false
    search_index_only: false

    navigation_depth: 2

#strict: true

plugins:
    # to get last revision date from git repo rather than page meta
    - git-revision-date-localized

    # allow docs_dir to begin at "."
#    - same-dir

    # allow sections to have their own pages
    - section-index

#    - search

extra_css:
    # code styles for the codehilite extension
    - css/code_styles.css

nav:
    - Home: index.md
    - Download: download.md
    - User Guide:
        - docs/index.md
        - Getting Started: docs/getting-started.md
        - Preferences: docs/preferences.md
        - Integrations: docs/integrations.md
    - Contributing:
        - docs/contributing/index.md
        - Development: docs/contributing/development.md
        - Documentation: docs/contributing/documentation.md
        - Translating: docs/contributing/translating.md
        - Maintainers: docs/contributing/maintainers.md


# Extensions
# See https://python-markdown.github.io/extensions/
markdown_extensions:
#    - admonition
    - attr_list
    - def_list
    - extra
    - toc:
        permalink: true
    - codehilite

# TODO:
# - strikethrough is not working


#  - sane_lists
#  - admonition
#  - abbr
#  - footnotes
#  - md_in_html
#  - pymdownx.arithmatex:
#      generic: true
#  - pymdownx.betterem:
#      smart_enable: all
#  - pymdownx.caret
#  - pymdownx.critic
#  - pymdownx.details
#  - pymdownx.inlinehilite
#  - pymdownx.keys
#  - pymdownx.mark
#  - pymdownx.smartsymbols
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_code_format
#  - pymdownx.tabbed
#  - pymdownx.tasklist:
#      custom_checkbox: true
#  - pymdownx.tilde
#  - pymdownx.highlight
#  - pymdownx.magiclink:
#      repo_url_shorthand: true
#      user: gnome-pomodoro
#      repo: gnome-pomodoro
#  - pymdownx.extra

# TODO: ENABLE search plugin 
# TODO: include Download and release info above footer


# Home Page navbar
# - About (a quick summary / hero)
# - Features (list of features)
# - Docs (link to docs)
# - Download (link to download page)  # / User must select their GNOME Shell version)

# Documentation
#nav:
#    - Home: 'index.md'
##    - About: 
#    - Download: 'download.md'
#    - User Guide:
#        - Getting Started: 'docs/getting-started.md'
#    #        (assumes user has downloaded the app, if not it provides links)
#    #        - Enable Extension
#    #        - Pomodoro Technique & Time Boxing
#        - Preferences: 'docs/preferences.md'
#        - Integrations: 'docs/integrations.md'
#    #        - Custom Actions
#    #        - DBus
#    #        - ...
#    - Contributing:
#        - Overview: 'docs/contributing/overview.md'
#        - Development: 'docs/contributing/development.md'
##            - Getting Code
##            - Setting up development envirionment
##            - Building from source
##            - Style Guide
##            - Writing Tests
#        - Documentation: 'docs/contributing/documentation.md'
#        - Translating: 'docs/contributing/translating.md'
#        - Maintainers: 'docs/contributing/maintainers.md'
##            - Releasing a version
##    - Support: 'support.md'
##        - Reporting issues
##        - Asking a question

##    - Test Page: 'test-page.md'

